### ISSUE TITLE
Send any kb/mouse inputs to games based on dinput/dinput8 

### ISSUE THREAD

**Issue by gegenoketaru** [elishacloud/DirectX-Wrappers#1]
I'm looking for a DirectInput/DirectInput8 solution to send any keyboard/mouse input to the games based on dinput/dinput8. So, is there any sample in **DirectX-Wrappers** ?

**Comment by elishacloud** [comment]
@eipeipkrop7992, I created a DirectInput converter that converts DirectInput games to DirectInput8.  You can check it out here: [dinputto8](https://github.com/elishacloud/dinputto8)

**Comment by elishacloud** [comment]
You may also want to check out this project: [DirectX_Hacks_for_TLoH](https://github.com/ChronoMonochrome/DirectX_Hacks_for_TLoH)

Closing issue.
