### ISSUE TITLE
Force Feedback

### ISSUE THREAD

**Issue by sonik-br** [elishacloud/DirectX-Wrappers#6]
Hi!
I found this project while searching for a way to to a dinput wrapper...
I want to intercept dinput calls and change the FFB Effects before sending them to the real dinput.
This project can help me with that? There's any starting guide?

My goal is to:
1: Adjust the `Gain` on the effect/device. This is useful for games that does not have this feature.
2: Fix FFB problems with older games. Like Need for Speed 2 sending 4 axis effects to 2 axis devices (and dinput does not allow this).

**Comment by elishacloud** [comment]
Hello,

Yes, this project can do everything you want.  It already intercepts dinput calls and effects.  You just need to add your code to it.

For dinput you can find the code under the [dinput](https://github.com/elishacloud/DirectX-Wrappers/tree/master/dinput) folder.

For effects you can find the code under the [IDirectInputEffect.cpp](https://github.com/elishacloud/DirectX-Wrappers/blob/master/dinput/IDirectInputEffect.cpp) file.

When you compile this whole solution it will make lots of dll files which you may no need or want.  But, you can remove all of the other projects out of this solution and just keep the dinput project.

Once you compile the project it will create a dinput.dll file that you can then place in the game's folder.  Keep in mind that dinput and dinput8 are two different projects so you will need to figure out if the game is dinput or dinput8.  If you have any specific questions you can ask them and I will try and answer them.

**Comment by sonik-br** [comment]
Thank you!

Dinput should work for me. I'm doing this for very old games :)

On another subject, I also want to do a wrapper for another dll that's not part of directx.
It's the old `iforce2.dll`.
It was the default forcefeedback api used by games before the deal with microsoft to merge it on dinput.
Any tip on how to do my own wrapper for this dll? This might be way above my coding skills but I still want to try. So many good old games that does not work correctly on new hardware (and new windows)

**Comment by elishacloud** [comment]
> Dinput should work for me. I'm doing this for very old games :)

I do have [another project](https://github.com/elishacloud/dinputto8) that converts dinput to dinput8.  If you want to use that then you can use other off-the-shelf tools for dinput8.  Or you could do your work on dinput8 instead.

> It's the old `iforce2.dll`. ...  Any tip on how to do my own wrapper for this dll?

You need to find all the exports of the dll and create a new dll with all those exports.   Just forward the ones you don't need into the "real" `iforce2.dll` and then the exports you want you can implement all the functions, similar to what you see with the dinput project.

**Comment by sonik-br** [comment]
Interesting.
For the iforce thing, I need to set memory address for the functions? Or just build a new dll with the same exports?
I think the oficial sdk should have a include `iforce2.h` file. Need to check.

**Comment by elishacloud** [comment]
You should not need any memory addresses if you use the header.  Just look at how it was done for dinput.  You can just build a new dll with the same exports and then forward the exports and functions to the real `iforce2.dll`.

**Comment by sonik-br** [comment]
Amazing!
Thank you very much.

**Comment by elishacloud** [comment]
You're welcome.
